using System.ComponentModel.DataAnnotations;

namespace SiemCore.Models
{
    /// <summary>
    /// Represents a security alert generated by the SIEM system
    /// </summary>
    public class Alert
    {
        [Key]
        public Guid Id { get; set; } = Guid.NewGuid();
        
        [Required]
        [StringLength(200)]
        public string Title { get; set; } = string.Empty;
        
        [Required]
        public string Description { get; set; } = string.Empty;
        
        [Required]
        [StringLength(20)]
        public AlertSeverity Severity { get; set; }
        
        [Required]
        [StringLength(50)]
        public AlertStatus Status { get; set; } = AlertStatus.Open;
        
        [Required]
        [StringLength(100)]
        public string RuleName { get; set; } = string.Empty;
        
        public Guid RuleId { get; set; }
        
        public List<Guid> RelatedEventIds { get; set; } = new List<Guid>();
        
        [StringLength(100)]
        public string AssignedTo { get; set; } = string.Empty;
        
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        
        public DateTime? UpdatedAt { get; set; }
        
        public DateTime? ResolvedAt { get; set; }
        
        public string Resolution { get; set; } = string.Empty;
        
        public Dictionary<string, object> Metadata { get; set; } = new Dictionary<string, object>();
        
        public int FalsePositiveScore { get; set; } = 0;
        
        public bool IsAutomatedResponse { get; set; } = false;
        public Guid SourceEventId { get; set; }
        public string AgentId { get; set; }
        public string SourceIp { get; set; }
        public string Username { get; set; }
        public int EventCount { get; set; }
        public DateTime FirstEventTime { get; set; }
        public DateTime LastEventTime { get; set; }
    }
    
    public enum AlertSeverity
    {
        Low = 1,
        Medium = 2,
        High = 3,
        Critical = 4
    }
    
    public enum AlertStatus
    {
        Open,
        InProgress,
        Resolved,
        FalsePositive,
        Closed
    }
}
